version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
    volumes:
      - ./data/:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped